### ISSUE TITLE
Cannot stop grunt watch process

### ISSUE THREAD

**Issue by CurtisBelt** [kyte-group/npm-bower-grunt-sass#1]
This works great but I'm running into one problem.

When I used to have grunt installed bare metal, it was a simple Ctrl-C to cancel the watch process.

But via docker, it doesn't let me kill this. Any ideas? Thanks!

![image](https://user-images.githubusercontent.com/4251760/32788103-f80c3212-c91d-11e7-8327-79d6748f64f5.png)

**Comment by aramalipoor** [comment]
Yes, I guess you need to add `-it` flags to the `docker run` command.

**Comment by CurtisBelt** [comment]
That did it, thank you!
